name: Build ESPHome firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup ESPHome
        run: |
          pip install esphome

      - name: Clean cache
        run: |
          rm -rf .esphome
          rm -rf build

      - name: Compile firmware
        run: |
          esphome run openhasp_pastel.yaml
